"""Add timezone column to User model

Revision ID: 04404fccf0f9
Revises: 06a7a273b362
Create Date: 2025-03-19 21:21:57.850177

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04404fccf0f9'
down_revision = '06a7a273b362'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timezone', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('timezone')

    # ### end Alembic commands ###
