"""Add temp_accounts column to SimpleFin model

Revision ID: 06a7a273b362
Revises: 29a4188fc690
Create Date: 2025-03-18 23:25:49.630350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a7a273b362'
down_revision = '29a4188fc690'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_id', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('external_id')

    # ### end Alembic commands ###
