"""Add temp_accounts column to SimpleFin model

Revision ID: 29a4188fc690
Revises: 
Create Date: 2025-03-18 23:22:28.063871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29a4188fc690'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('simplefin_settings')
    with op.batch_alter_table('SimpleFin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_accounts', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('SimpleFin', schema=None) as batch_op:
        batch_op.drop_column('temp_accounts')

    op.create_table('simplefin_settings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=120), nullable=False),
    sa.Column('access_url', sa.TEXT(), nullable=False),
    sa.Column('last_sync', sa.DATETIME(), nullable=True),
    sa.Column('enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('sync_frequency', sa.VARCHAR(length=20), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###
